### PR TITLE
Update View.php

### PR DESCRIPTION
**Pull request by priteshkhetani**
In _getSummaryFilesHash() function $file should be processed to remove web path.

### CODE REVIEW

**Comment by rmrevin** [comment]
Please add the unit test for this case

**Comment by priteshkhetani** [comment]
@rmrevin  I don't have much knowledge about unit testing.

**Comment by rmrevin** [comment]
@priteshkhetani This is an excellent opportunity to learn. I can not test your request without unit tests.

**Comment by rmrevin** [comment]
Already implemented. Thanks.

**Pull request closed without merging**
